name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libfreetype-dev build-essential

      - name: Run Build
        run: |
          make all_

      - name: Save Server
        uses: actions/upload-artifact@v2
        with:
          name: skat_server
          path: skat_server

      - name: Save Client
        uses: actions/upload-artifact@v2
        with:
          name: skat_client
          path: skat_client
